name: Flymovies Actions
run-name: ${{ github.actor }} building app flymovies 🚀
on: 
  push:

jobs:
  build-and-release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Install project dependencies
        run: flutter pub get
    #  - name: Run Analyze
    #    run: flutter analyze
    #  - name: Run Tests
    #    run: flutter test
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build installer msix
        run: dart run msix:create
      - name: Windows Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/windows/runner/Release/flymovies.msix
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.${{ github.run_number }}w

  build-and-release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - run: flutter build linux --release
      - name: Pack Linux
        run: |
             dart pub global activate flutter_to_debian
             flutter_to_debian
      - name: Linux Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "debian/packages/FlyMovies_1.0.0.0_amd64.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.${{ github.run_number }}l
