name: Flymovies Actions
run-name: ${{ github.actor }} building app flymovies 🚀
on: 
  push:

jobs:
  build-and-release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Enable Flutter Distributor
        run: dart pub global activate flutter_distributor
      - name: Install project dependencies
        run: flutter pub get
    #  - name: Run Analyze
    #    run: flutter analyze
    #  - name: Run Tests
    #    run: flutter test
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
    #  - name: Build Windows
    #    run: flutter build windows
    #  - name: Build Installer
    #    run: dart run msix:create
      - name: Build installer
        run: flutter_distributor release --name dev --jobs=release-dev-windows
      - name: Windows Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/flymovies*.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.${{ github.run_number }}w

  build-and-release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libsqlite3-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build installer
        run: flutter_distributor release --name dev --jobs=release-dev-linux
      - name: Linux Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/flymovies*.deb
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.${{ github.run_number }}l